import type { AssistantConfig, ResumeData } from './types'

export const resumeData: ResumeData = {
  name: 'Anthony AL Helou',
  title: 'Senior Software Engineer',
  contact:
    'anthony_alhelou@live.com | +961 70 687159 | Bsaba, Baabda, Lebanon',
  dateOfBirth: '01/02/1991',
  nationality: 'Lebanese',
  about:
    'Software Engineer with over 10 years of experience, including 6 years focused on frontend development. Recognized for strengths in UI architecture, state management, and performance optimization, which enhance user experience. Adept at testing and documentation while collaborating in agile teams. Proficient in Python, Node.js, and PHP, offering a well-rounded skill set to drive impactful software solutions.',
  experiences: [
    {
      role: 'Senior Software Engineer',
      company: 'Novelus',
      period: '01/2026 - Present',
      location: 'Baouchriyeh, Lebanon',
      highlights: [
        'Part of the framework team building common components that serve as the foundation of the project.',
        'Introduced Storybook and unit testing to improve quality and component documentation.',
        'Contributed to a microfrontend-based project hosted on Azure and created pipelines to improve push processes and maintain a cleaner codebase.',
      ],
    },
    {
      role: 'Senior Software Engineer - Frontend',
      company: 'Pennylane',
      period: '10/2021 - 10/2025',
      location: 'Paris (remote), France',
      highlights: [
        'Developed interactive data-insight tools for non-accountants using Highcharts and Recharts.',
        'Created dynamic KPI and trend tables with strong accessibility and responsive behavior.',
        'Owned end-to-end delivery by refining tickets and coordinating with design, product, and QA.',
        'Established QA processes and structured retrospectives for continuous team improvement.',
        'Stack: ReactJS, TypeScript, JavaScript, TanStack Query, React Context.',
      ],
    },
    {
      role: 'Software Engineer',
      company: 'Cedrus Digital',
      period: '01/2021 - 10/2021',
      location: 'Beirut, Lebanon',
      highlights: [
        "Led a major refactor of the application's architecture to modularize the system and speed up feature implementation.",
        'Delivered new features and UI enhancements, including tailored enterprise client projects.',
        'Implemented targeted backend updates to optimize performance.',
        'Facilitated Agile ceremonies and collaborated closely with clients.',
        'Stack: Angular, TypeScript, JavaScript.',
      ],
    },
    {
      role: 'Software Engineer',
      company: 'SerVme',
      period: '06/2020 - 09/2020',
      location: 'Beirut, Lebanon',
      highlights: [
        'Led migration from AngularJS to React, improving performance and user experience.',
        'Developed a reusable component system to reduce redundancy and speed up future development.',
        'Acted as Scrum Master, facilitating ceremonies and removing blockers.',
        'Contributed to Lumen APIs to improve backend efficiency and scalability.',
        'Stack: ReactJS, TypeScript, JavaScript, PHP.',
      ],
    },
    {
      role: 'Software Engineer',
      company: 'Administrate',
      period: '08/2017 - 06/2020',
      location: 'Beirut, Lebanon',
      highlights: [
        'Developed and shipped core features across frontend and backend.',
        'Led migration from AngularJS to React to modernize the tech stack.',
        'Defined SQL and API schemas and strengthened code quality with unit tests.',
        'Guided Agile execution as Scrum Master through standups, planning, and retrospectives.',
        'Stack: Python, Node.js, GraphQL, ReactJS, TypeScript, JavaScript.',
      ],
    },
    {
      role: 'Software Engineer',
      company: 'Keeward',
      period: '09/2015 - 08/2017',
      location: 'Beirut, Lebanon',
      highlights: [
        'Developed a CodeIgniter lead-ingestion tool to improve marketing pipelines and targeting.',
        'Maintained Git repositories to keep code management efficient.',
        'Automated builds and deployments with CircleCI and Docker.',
        'Stack: EmberJS, Ruby on Rails.',
      ],
    },
    {
      role: 'Web Developer',
      company: 'InMobiles',
      period: '10/2013 - 09/2015',
      location: 'Beirut, Lebanon',
      highlights: [
        'Developed e-commerce solutions with payment integrations.',
        'Created and maintained CRM systems and APIs using PHP and CodeIgniter.',
        'Collaborated with cross-functional teams to ensure smooth integrations.',
        'Stack: PHP, JavaScript, HTML, CSS.',
      ],
    },
  ],
  projects: [],
  skills: [
    'ReactJS',
    'JavaScript (ES6+)',
    'TypeScript',
    'TanStack Query',
    'React Testing Library',
    'E2E Testing',
    'React Context',
    'Redux',
    'Highcharts',
    'Recharts',
    'Angular',
    'HTML5',
    'CSS3',
    'SCSS',
    'Tailwind CSS',
    'Storybook',
    'Python',
    'Node.js',
    'PHP',
    'GraphQL',
    'REST',
    'GitHub',
    'Notion',
    'Docker',
    'Azure',
    'Husky',
  ],
  education: [
    {
      degree: 'Computer and Telecommunication Engineering | Masters',
      school: 'Antonine University',
      period: '09/2008 - 07/2013',
      location: 'Baabda, Lebanon',
    },
    {
      degree: "Lebanese Bachelor's Degree in Life Science",
      school: 'Antonine Fathers School',
      period: '09/1992 - 07/2008',
      location: 'Baabda, Lebanon',
    },
  ],
  languages: ['Arabic', 'English', 'French'],
}

export const suggestedQuestions = [
  'What experience does Anthony have?',
  "What are Anthony's core skills?",
  'Where has Anthony worked recently?',
  'How can I contact Anthony?',
  "What is Anthony's education?",
]

export const assistantConfig: AssistantConfig = {
  mode: 'mock',
  endpoint: '/api/chat',
  requestTimeoutMs: 8000,
  mockDelayMs: 500,
}
